### ISSUE TITLE
transfer fund error!

### ISSUE THREAD

**Issue by DenisRuparel** [adrianhajdin/banking#21]
**when i transfer the funds i face this error**
Transfer fund failed:  Error: {"code":"ValidationError","message":"Validation error(s) present. See embedded errors list for more details.","_embedded":{"errors":[{"code":"Invalid","message":"Invalid destination.","path":"/_links/destination/href","_links":{}}]}}
    at errorFrom (webpack-internal:///(rsc)/./node_modules/dwolla-v2/src/dwolla/Token.js:52:15)
    at eval (webpack-internal:///(rsc)/./node_modules/dwolla-v2/src/dwolla/Token.js:73:29)
From previous event:
    at handleResponse (webpack-internal:///(rsc)/./node_modules/dwolla-v2/src/dwolla/Token.js:60:21)
From previous event:
    at Token.post (webpack-internal:///(rsc)/./node_modules/dwolla-v2/src/dwolla/Token.js:95:6)
    at eval (webpack-internal:///(rsc)/./node_modules/dwolla-v2/src/dwolla/Client.js:66:25)
    at process.processImmediate (node:internal/timers:478:21)
    at process.callbackTrampoline (node:internal/async_hooks:130:17)
From previous event:
    at Client.post (webpack-internal:///(rsc)/./node_modules/dwolla-v2/src/dwolla/Client.js:65:23)
    at $$ACTION_3 (webpack-internal:///(rsc)/./lib/actions/dwolla.actions.ts:86:35)
    at endpoint (webpack-internal:///(rsc)/./node_modules/next/dist/build/webpack/loaders/next-flight-action-entry-loader.js?actions=%5B%5B%22D%3A%5C%5CNext_Projects%5C%5Cbanking%5C%5Clib%5C%5Cactions%5C%5Cbank.actions.ts%22%2C%5B%22getAccount%22%2C%22getInstitution%22%2C%22getAccounts%22%2C%22%24%24ACTION_2%22%2C%22%24%24ACTION_3%22%2C%22%24%24ACTION_1%22%2C%22%24%24ACTION_0%22%2C%22getTransactions%22%5D%5D%2C%5B%22D%3A%5C%5CNext_Projects%5C%5Cbanking%5C%5Clib%5C%5Cactions%5C%5Ctransaction.actions.ts%22%2C%5B%22getTransactionsByBankId%22%2C%22%24%24ACTION_1%22%2C%22createTransaction%22%2C%22%24%24ACTION_0%22%5D%5D%2C%5B%22D%3A%5C%5CNext_Projects%5C%5Cbanking%5C%5Clib%5C%5Cappwrite.ts%22%2C%5B%22createSessionClient%22%2C%22createAdminClient%22%5D%5D%2C%5B%22D%3A%5C%5CNext_Projects%5C%5Cbanking%5C%5Clib%5C%5Cactions%5C%5Cuser.actions.ts%22%2C%5B%22%24%24ACTION_9%22%2C%22%24%24ACTION_2%22%2C%22%24%24ACTION_7%22%2C%22createLinkToken%22%2C%22getUserInfo%22%2C%22getBankByAccountId%22%2C%22%24%24ACTION_5%22%2C%22%24%24ACTION_0%22%2C%22%24%24ACTION_1%22%2C%22%24%24ACTION_4%22%2C%22createBankAccount%22%2C%22signIn%22%2C%22%24%24ACTION_3%22%2C%22signUp%22%2C%22getBanks%22%2C%22getBank%22%2C%22%24%24ACTION_6%22%2C%22exchangePublicToken%22%2C%22%24%24ACTION_8%22%2C%22logoutAccount%22%2C%22getLoggedInUser%22%5D%5D%2C%5B%22D%3A%5C%5CNext_Projects%5C%5Cbanking%5C%5Clib%5C%5Cactions%5C%5Cdwolla.actions.ts%22%2C%5B%22%24%24ACTION_4%22%2C%22createTransfer%22%2C%22addFundingSource%22%2C%22%24%24ACTION_1%22%2C%22createDwollaCustomer%22%2C%22%24%24ACTION_3%22%2C%22createOnDemandAuthorization%22%2C%22createFundingSource%22%2C%22%24%24ACTION_0%22%2C%22%24%24ACTION_2%22%5D%5D%5D&__client_imported__=!:52:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async D:\Next_Projects\banking\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:39:418
    at async rS (D:\Next_Projects\banking\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:38:7978)      
    at async r2 (D:\Next_Projects\banking\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:41:1251)      
    at async doRender (D:\Next_Projects\banking\node_modules\next\dist\server\base-server.js:1438:30)
    at async cacheEntry.responseCache.get.routeKind (D:\Next_Projects\banking\node_modules\next\dist\server\base-server.js:1599:28)
    at async DevServer.renderToResponseWithComponentsImpl (D:\Next_Projects\banking\node_modules\next\dist\server\base-server.js:1507:28)
    at async DevServer.renderPageComponent (D:\Next_Projects\banking\node_modules\next\dist\server\base-server.js:1924:24)  
    at async DevServer.renderToResponseImpl (D:\Next_Projects\banking\node_modules\next\dist\server\base-server.js:1962:32) 
    at async DevServer.pipeImpl (D:\Next_Projects\banking\node_modules\next\dist\server\base-server.js:920:25)
    at async NextNodeServer.handleCatchallRenderRequest (D:\Next_Projects\banking\node_modules\next\dist\server\next-server.js:272:17)
    at async DevServer.handleRequestImpl (D:\Next_Projects\banking\node_modules\next\dist\server\base-server.js:816:17)     
    at async D:\Next_Projects\banking\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (D:\Next_Projects\banking\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (D:\Next_Projects\banking\node_modules\next\dist\server\dev\next-dev-server.js:336:24) 
    at async invokeRender (D:\Next_Projects\banking\node_modules\next\dist\server\lib\router-server.js:174:21)
    at async handleRequest (D:\Next_Projects\banking\node_modules\next\dist\server\lib\router-server.js:353:24)
    at async requestHandlerImpl (D:\Next_Projects\banking\node_modules\next\dist\server\lib\router-server.js:377:13)        
    at async Server.requestListener (D:\Next_Projects\banking\node_modules\next\dist\server\lib\start-server.js:141:13) {   
  status: 400,
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      date: [Array],
      'content-type': [Array],
      'content-length': [Array],
      connection: [Array],
      'access-control-allow-origin': [Array],
      'x-request-id': [Array],
      'cf-cache-status': [Array],
      'set-cookie': [Array],
      server: [Array],
      'cf-ray': [Array]
    }
  },
  body: {
    code: 'ValidationError',
    message: 'Validation error(s) present. See embedded errors list for more details.',
    _embedded: { errors: [Array] }
  }
}

**Comment by DenisRuparel** [comment]
> Hola, como estas?, sabes que primero cambie las variables "SharablesId" por "SHAREABLEID "(en minúscula, solo que lo coloque en mayúscula para que lo leas perfecto) y luego me fui a bank.actions.ts y le saque al comentario a todo el código que estaba comentado y funciono. Saludos

Thanks dear

**Comment by aryanyashishere** [comment]
still same error is coming 

> Hola, como estas?, sabes que primero cambie las variables "SharablesId" por "SHAREABLEID "(en minúscula, solo que lo coloque en mayúscula para que lo leas perfecto) y luego me fui a bank.actions.ts y le saque al comentario a todo el código que estaba comentado y funciono. Saludos
