### ISSUE TITLE
Missing required attribute "userid"

### ISSUE THREAD

**Issue by XaskyZ** [adrianhajdin/banking#22]
`Error AppwriteException [Error]: Invalid document structure: Missing required attribute "userid"
    at Client.call (webpack-internal:///(action-browser)/./node_modules/node-appwrite/lib/client.js:206:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Databases.createDocument (webpack-internal:///(action-browser)/./node_modules/node-appwrite/lib/services/databases.js:1711:16)
    at async $$ACTION_2 (webpack-internal:///(action-browser)/./lib/actions/user.actions.ts:95:25)
    at async C:\Users\xasky\Documents\Programming\banking-main\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:39:418
    at async rS (C:\Users\xasky\Documents\Programming\banking-main\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:38:7978)
    at async r2 (C:\Users\xasky\Documents\Programming\banking-main\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:41:1251)
    at async doRender (C:\Users\xasky\Documents\Programming\banking-main\node_modules\next\dist\server\base-server.js:1438:30)
    at async cacheEntry.responseCache.get.routeKind (C:\Users\xasky\Documents\Programming\banking-main\node_modules\next\dist\server\base-server.js:1599:28)
    at async DevServer.renderToResponseWithComponentsImpl (C:\Users\xasky\Documents\Programming\banking-main\node_modules\next\dist\server\base-server.js:1507:28)
    at async DevServer.renderPageComponent (C:\Users\xasky\Documents\Programming\banking-main\node_modules\next\dist\server\base-server.js:1924:24)
    at async DevServer.renderToResponseImpl (C:\Users\xasky\Documents\Programming\banking-main\node_modules\next\dist\server\base-server.js:1962:32)
    at async DevServer.pipeImpl (C:\Users\xasky\Documents\Programming\banking-main\node_modules\next\dist\server\base-server.js:920:25)
    at async NextNodeServer.handleCatchallRenderRequest (C:\Users\xasky\Documents\Programming\banking-main\node_modules\next\dist\server\next-server.js:272:17)
    at async DevServer.handleRequestImpl (C:\Users\xasky\Documents\Programming\banking-main\node_modules\next\dist\server\base-server.js:816:17)
    at async C:\Users\xasky\Documents\Programming\banking-main\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (C:\Users\xasky\Documents\Programming\banking-main\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (C:\Users\xasky\Documents\Programming\banking-main\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (C:\Users\xasky\Documents\Programming\banking-main\node_modules\next\dist\server\lib\router-server.js:174:21)
    at async handleRequest (C:\Users\xasky\Documents\Programming\banking-main\node_modules\next\dist\server\lib\router-server.js:353:24)
    at async requestHandlerImpl (C:\Users\xasky\Documents\Programming\banking-main\node_modules\next\dist\server\lib\router-server.js:377:13)
    at async Server.requestListener (C:\Users\xasky\Documents\Programming\banking-main\node_modules\next\dist\server\lib\start-server.js:141:13) {
  code: 400,
  type: 'document_invalid_structure',
  response: {
    message: 'Invalid document structure: Missing required attribute "userid"',
    code: 400,
    type: 'document_invalid_structure',
    version: '1.5.7'
  }
}`

**Comment by ktglez02** [comment]
it's supposed to be userId capital I

**Comment by vedant03ingole** [comment]
Go to the appwrite console and check for the attributes in the collections.
