### ISSUE TITLE
appwrite exception error query error error getting account from plaid

### ISSUE THREAD

**Issue by AyushSinghChauhan21** [adrianhajdin/banking#28]
AppwriteException: Invalid query: Query value is invalid for attribute "$id"
    at _Client.call (webpack-internal:///(rsc)/./node_modules/node-appwrite/dist/client.mjs:283:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Databases.listDocuments (webpack-internal:///(rsc)/./node_modules/node-appwrite/dist/services/databases.mjs:1581:12)
    at async $$ACTION_8 (webpack-internal:///(rsc)/./lib/actions/user.actions.ts:235:22)
    at async $$ACTION_1 (webpack-internal:///(rsc)/./lib/actions/bank.actions.ts:77:22)
    at async Home (webpack-internal:///(rsc)/./app/(root)/page.tsx:45:21) {
  code: 400,
  type: 'general_query_invalid',
  response: {
    message: 'Invalid query: Query value is invalid for attribute "$id"',
    code: 400,
    type: 'general_query_invalid',
    version: '1.5.7'
  }
}
An error occurred while getting the account: TypeError: Cannot read properties of undefined (reading 'accessToken')
    at $$ACTION_1 (webpack-internal:///(rsc)/./lib/actions/bank.actions.ts:82:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Home (webpack-internal:///(rsc)/./app/(root)/page.tsx:45:21)
 GET /?_rsc=mua4a 200 in 2396ms
AppwriteException: Invalid query: Query value is invalid for attribute "$id"
    at _Client.call (webpack-internal:///(rsc)/./node_modules/node-appwrite/dist/client.mjs:283:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Databases.listDocuments (webpack-internal:///(rsc)/./node_modules/node-appwrite/dist/services/databases.mjs:1581:12)
    at async $$ACTION_8 (webpack-internal:///(rsc)/./lib/actions/user.actions.ts:235:22)
    at async $$ACTION_1 (webpack-internal:///(rsc)/./lib/actions/bank.actions.ts:77:22)
    at async Home (webpack-internal:///(rsc)/./app/(root)/page.tsx:45:21) {
  code: 400,
  type: 'general_query_invalid',
  response: {
    message: 'Invalid query: Query value is invalid for attribute "$id"',
    code: 400,
    type: 'general_query_invalid',
    version: '1.5.7'
  }
}
An error occurred while getting the account: TypeError: Cannot read properties of undefined (reading 'accessToken')
    at $$ACTION_1 (webpack-internal:///(rsc)/./lib/actions/bank.actions.ts:82:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Home (webpack-internal:///(rsc)/./app/(root)/page.tsx:45:21)
 GET /?_rsc=mua4a 200 in 2429ms
AppwriteException: Invalid query: Query value is invalid for attribute "$id"
    at _Client.call (webpack-internal:///(rsc)/./node_modules/node-appwrite/dist/client.mjs:283:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Databases.listDocuments (webpack-internal:///(rsc)/./node_modules/node-appwrite/dist/services/databases.mjs:1581:12)
    at async $$ACTION_8 (webpack-internal:///(rsc)/./lib/actions/user.actions.ts:235:22)
    at async $$ACTION_1 (webpack-internal:///(rsc)/./lib/actions/bank.actions.ts:77:22)
    at async Home (webpack-internal:///(rsc)/./app/(root)/page.tsx:45:21) {
  code: 400,
  type: 'general_query_invalid',
  response: {
    message: 'Invalid query: Query value is invalid for attribute "$id"',
    code: 400,
    type: 'general_query_invalid',
    version: '1.5.7'
  }
}
An error occurred while getting the account: TypeError: Cannot read properties of undefined (reading 'accessToken')
    at $$ACTION_1 (webpack-internal:///(rsc)/./lib/actions/bank.actions.ts:82:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Home (webpack-internal:///(rsc)/./app/(root)/page.tsx:45:21)
 GET / 200 in 2978ms
 POST / 200 in 199ms
 POST / 200 in 277ms
 POST / 200 in 275ms
Creating a Funding Source Failed:  Error: {"code":"DuplicateResource","message":"Bank already exists: id=7dae9be1-07a7-40eb-ab05-87da6ca52072","_links":{"about":{"href":"https://api-sandbox.dwolla.com/funding-sources/7dae9be1-07a7-40eb-ab05-87da6ca52072","type":"application/vnd.dwolla.v1.hal+json","resource-type":"funding-source"}}}
    at errorFrom (webpack-internal:///(rsc)/./node_modules/dwolla-v2/src/dwolla/Token.js:52:15)
    at eval (webpack-internal:///(rsc)/./node_modules/dwolla-v2/src/dwolla/Token.js:73:29)
From previous event:
    at handleResponse (webpack-internal:///(rsc)/./node_modules/dwolla-v2/src/dwolla/Token.js:60:21)
From previous event:
    at Token.post (webpack-internal:///(rsc)/./node_modules/dwolla-v2/src/dwolla/Token.js:95:6)
    at eval (webpack-internal:///(rsc)/./node_modules/dwolla-v2/src/dwolla/Client.js:66:25)
    at process.processImmediate (node:internal/timers:478:21)
    at process.callbackTrampoline (node:internal/async_hooks:130:17)
From previous event:
    at Client.post (webpack-internal:///(rsc)/./node_modules/dwolla-v2/src/dwolla/Client.js:65:23)
    at $$ACTION_0 (webpack-internal:///(rsc)/./lib/actions/dwolla.actions.ts:43:35)
    at $$ACTION_4 (webpack-internal:///(rsc)/./lib/actions/dwolla.actions.ts:103:22)
    at async $$ACTION_6 (webpack-internal:///(rsc)/./lib/actions/user.actions.ts:192:34)
    at async /Users/ayush/Desktop/banking_project/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:418
    at async rS (/Users/ayush/Desktop/banking_project/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:38:7978)
    at async r2 (/Users/ayush/Desktop/banking_project/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:41:1251)
    at async doRender (/Users/ayush/Desktop/banking_project/node_modules/next/dist/server/base-server.js:1438:30)
    at async cacheEntry.responseCache.get.routeKind (/Users/ayush/Desktop/banking_project/node_modules/next/dist/server/base-server.js:1599:28)
    at async DevServer.renderToResponseWithComponentsImpl (/Users/ayush/Desktop/banking_project/node_modules/next/dist/server/base-server.js:1507:28)
    at async DevServer.renderPageComponent (/Users/ayush/Desktop/banking_project/node_modules/next/dist/server/base-server.js:1924:24)
    at async DevServer.renderToResponseImpl (/Users/ayush/Desktop/banking_project/node_modules/next/dist/server/base-server.js:1962:32)
    at async DevServer.pipeImpl (/Users/ayush/Desktop/banking_project/node_modules/next/dist/server/base-server.js:920:25)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/ayush/Desktop/banking_project/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/Users/ayush/Desktop/banking_project/node_modules/next/dist/server/base-server.js:816:17)
    at async /Users/ayush/Desktop/banking_project/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Users/ayush/Desktop/banking_project/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/Users/ayush/Desktop/banking_project/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/Users/ayush/Desktop/banking_project/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/Users/ayush/Desktop/banking_project/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/Users/ayush/Desktop/banking_project/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/Users/ayush/Desktop/banking_project/node_modules/next/dist/server/lib/start-server.js:141:13) {
  status: 400,
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      date: [Array],
      'content-type': [Array],
      'content-length': [Array],
      connection: [Array],
      'access-control-allow-origin': [Array],
      'x-request-id': [Array],
      'cf-cache-status': [Array],
      'set-cookie': [Array],
      server: [Array],
      'cf-ray': [Array]
    }
  },
  body: {
    code: 'DuplicateResource',
    message: 'Bank already exists: id=7dae9be1-07a7-40eb-ab05-87da6ca52072',
    _links: { about: [Object] }
  }
}
An error occured while creating exchanging token: [Function: Error] { stackTraceLimit: 68, prepareStackTrace: undefined }
 POST / 200 in 5423ms
AppwriteException: Invalid query: Query value is invalid for attribute "$id"
    at _Client.call (webpack-internal:///(rsc)/./node_modules/node-appwrite/dist/client.mjs:283:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Databases.listDocuments (webpack-internal:///(rsc)/./node_modules/node-appwrite/dist/services/databases.mjs:1581:12)
    at async $$ACTION_8 (webpack-internal:///(rsc)/./lib/actions/user.actions.ts:235:22)
    at async $$ACTION_1 (webpack-internal:///(rsc)/./lib/actions/bank.actions.ts:77:22)
    at async Home (webpack-internal:///(rsc)/./app/(root)/page.tsx:45:21) {
  code: 400,
  type: 'general_query_invalid',
  response: {
    message: 'Invalid query: Query value is invalid for attribute "$id"',
    code: 400,
    type: 'general_query_invalid',
    version: '1.5.7'
  }
}
An error occurred while getting the account: TypeError: Cannot read properties of undefined (reading 'accessToken')
    at $$ACTION_1 (webpack-internal:///(rsc)/./lib/actions/bank.actions.ts:82:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Home (webpack-internal:///(rsc)/./app/(root)/page.tsx:45:21)
 GET /?_rsc=ls1f6 200 in 3515ms
 POST / 200 in 1108ms

**Comment by almostsultry** [comment]
Did you ever get this figured out? I have a similar problem.

**Comment by bustillos83** [comment]
Did you get to figure this out?

**Comment by almostsultry** [comment]
@bustillos83 Nope. Still waiting for someone to review my AppWrite screenshots for completeness on the [ticket](https://github.com/adrianhajdin/banking/issues/30) I opened.

**Comment by rayvego** [comment]
Solved!
https://github.com/adrianhajdin/banking/issues/30#issuecomment-2233797208
