### ISSUE TITLE
Validation error 

### ISSUE THREAD

**Issue by bustillos83** [adrianhajdin/banking#32]
I also get this Validation error when trying to sign up. 

[Symbol(map)]: [Object: null prototype] {
      date: [Array],
      'content-type': [Array],
      'content-length': [Array],
      connection: [Array],
      'access-control-allow-origin': [Array],
      'x-request-id': [Array],
      'cf-cache-status': [Array],
      'set-cookie': [Array],
      server: [Array],
      'cf-ray': [Array]
    }
  },
  body: {
    code: 'ValidationError',
    message: 'Validation error(s) present. See embedded errors list for more details.',
    _embedded: { errors: [Array] }
  }
}
Error Error: Error creating Dwolla customer
    at $$ACTION_1 (webpack-internal:///(rsc)/./lib/actions/user.actions.ts:61:39)
    at async C:\Users\fernandob\GitHub\fb_banking\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:39:418
    at async rw (C:\Users\fernandob\GitHub\fb_banking\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:38:7978)
    at async r4 (C:\Users\fernandob\GitHub\fb_banking\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:41:1251)
    at async doRender (C:\Users\fernandob\GitHub\fb_banking\node_modules\next\dist\server\base-server.js:1438:30)
    at async cacheEntry.responseCache.get.routeKind (C:\Users\fernandob\GitHub\fb_banking\node_modules\next\dist\server\base-server.js:1599:28)
    at async DevServer.renderToResponseWithComponentsImpl (C:\Users\fernandob\GitHub\fb_banking\node_modules\next\dist\server\base-server.js:1507:28)
    at async DevServer.renderPageComponent (C:\Users\fernandob\GitHub\fb_banking\node_modules\next\dist\server\base-server.js:1931:24)
    at async DevServer.renderToResponseImpl (C:\Users\fernandob\GitHub\fb_banking\node_modules\next\dist\server\base-server.js:1969:32)
    at async DevServer.pipeImpl (C:\Users\fernandob\GitHub\fb_banking\node_modules\next\dist\server\base-server.js:920:25)
    at async NextNodeServer.handleCatchallRenderRequest (C:\Users\fernandob\GitHub\fb_banking\node_modules\next\dist\server\next-server.js:272:17)
    at async DevServer.handleRequestImpl (C:\Users\fernandob\GitHub\fb_banking\node_modules\next\dist\server\base-server.js:816:17)
    at async C:\Users\fernandob\GitHub\fb_banking\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (C:\Users\fernandob\GitHub\fb_banking\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (C:\Users\fernandob\GitHub\fb_banking\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (C:\Users\fernandob\GitHub\fb_banking\node_modules\next\dist\server\lib\router-server.js:174:21)
    at async handleRequest (C:\Users\fernandob\GitHub\fb_banking\node_modules\next\dist\server\lib\router-server.js:353:24)
    at async requestHandlerImpl (C:\Users\fernandob\GitHub\fb_banking\node_modules\next\dist\server\lib\router-server.js:377:13)
    at async Server.requestListener (C:\Users\fernandob\GitHub\fb_banking\node_modules\next\dist\server\lib\start-server.js:141:13)

**Comment by bustillos83** [comment]
check my code [](https://github.com/bustillos83/fb_bankingl)

**Comment by LazarosZiskos** [comment]
Did anyone resolve this?? I get the same error. help

**Comment by bustillos83** [comment]
> Did anyone resolve this?? I get the same error. help

yes, i did make sure when you sign up that you use the correct format, for example for the birthdate i was using 11/11/91 when it suppose to be 11-11-91, so i guess forward slash was causing an issue.

**Comment by LazarosZiskos** [comment]
> > Did anyone resolve this?? I get the same error. help
> 
> yes, i did make sure when you sign up that you use the correct format, for example for the birthdate i was using 11/11/91 when it suppose to be 11-11-91, so i guess forward slash was causing an issue.

I tried that and every other combination.. nothing works 😔

**Comment by bustillos83** [comment]
how about zip code or state? everything correct format?

**Comment by LazarosZiskos** [comment]
> how about zip code or state? everything correct format?

Yes everything is as the video. One thing, I opted into not using a city input as it seemed unnecessary. Do you think that could trigger a dwolla error? Maybe it expects a city to work?

**Comment by bustillos83** [comment]
> > how about zip code or state? everything correct format?
> 
> Yes everything is as the video. One thing, I opted into not using a city input as it seemed unnecessary. Do you think that could trigger a dwolla error? Maybe it expects a city to work?

yeah i would assume so as if you copy some code from the repo there might be something pertaining to City there and maybe that is what's causing the issue.

**Comment by LazarosZiskos** [comment]
> > > how about zip code or state? everything correct format?
> > 
> > 
> > Yes everything is as the video. One thing, I opted into not using a city input as it seemed unnecessary. Do you think that could trigger a dwolla error? Maybe it expects a city to work?
> 
> yeah i would assume so as if you copy some code from the repo there might be something pertaining to City there and maybe that is what's causing the issue.

I didn't copy the code, i watched the tutorial and tried to recreate it. Anyway, turns out the city was the issue. I added it in the input,types and where it was necessary and it workes now!

Thanks for taking the time to help me mate! wish you all the best
