### ISSUE TITLE
Validation error sign up

### ISSUE THREAD

**Issue by boxlem** [adrianhajdin/banking#57]
I keep getting this error when I try to sign up 
status: 400,
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      date: [Array],
      'content-type': [Array],
      'content-length': [Array],
      connection: [Array],
      'access-control-allow-origin': [Array],
      'x-request-id': [Array],
      'cf-cache-status': [Array],
      'set-cookie': [Array],
      server: [Array],
      'cf-ray': [Array]
    }
  },
  body: {
    code: 'ValidationError',
    message: 'Validation error(s) present. See embedded errors list for more details.',
    _embedded: { errors: [Array] }
  }
}
Error Error: Error creating Dwolla customer

This is my code: https://github.com/boxlem/banking.git

**Comment by boxlem** [comment]
<img width="471" alt="Screenshot 2024-09-08 at 1 56 08 AM" src="https://github.com/user-attachments/assets/4076451d-1c3c-4777-889b-98c91362041b">

**Comment by joules65** [comment]
I get this same error too and haven't been able to figure why

**Comment by joules65** [comment]
Error: No session
    at createSessionClient (webpack-internal:///(rsc)/./lib/appwrite.ts:21:15)
    at getLoggedInUser (webpack-internal:///(rsc)/./lib/actions/user.actions.ts:115:97)
    at Home (webpack-internal:///(rsc)/./app/(root)/page.tsx:35:102)
    at eval (webpack-internal:///(rsc)/./node_modules/@sentry/nextjs/build/cjs/common/wrapServerComponentWithSentry.js:67:40)
    at Object.handleCallbackErrors (webpack-internal:///(rsc)/./node_modules/@sentry/core/build/cjs/utils/handleCallbackErrors.js:26:26)
    at eval (webpack-internal:///(rsc)/./node_modules/@sentry/nextjs/build/cjs/common/wrapServerComponentWithSentry.js:66:27)
    at eval (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:955:15)
    at Object.handleCallbackErrors (webpack-internal:///(instrument)/./node_modules/@sentry/core/build/cjs/utils/handleCallbackErrors.js:26:26)
    at eval (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:954:19)
    at AsyncLocalStorage.run (node:internal/async_local_storage/async_hooks:91:14)
    at SentryContextManager.with (webpack-internal:///(instrument)/./node_modules/@opentelemetry/context-async-hooks/build/src/AsyncLocalStorageContextManager.js:33:40)
    at SentryContextManager.with (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:1376:24)     
    at ContextAPI.with (webpack-internal:///(instrument)/./node_modules/@opentelemetry/api/build/esm/api/context.js:95:54)
    at Tracer.startActiveSpan (webpack-internal:///(instrument)/./node_modules/@opentelemetry/sdk-trace-base/build/esm/Tracer.js:136:76)
    at eval (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:953:19)
    at eval (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:1148:21)
    at Object.startSpanManual (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:946:10)
    at Object.startSpanManual (webpack-internal:///(rsc)/./node_modules/@sentry/core/build/cjs/tracing/trace.js:90:16)
    at eval (webpack-internal:///(rsc)/./node_modules/@sentry/nextjs/build/cjs/common/wrapServerComponentWithSentry.js:56:23)
    at eval (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:1250:14)
    at AsyncLocalStorage.run (node:internal/async_local_storage/async_hooks:91:14)
    at SentryContextManager.with (webpack-internal:///(instrument)/./node_modules/@opentelemetry/context-async-hooks/build/src/AsyncLocalStorageContextManager.js:33:40)
    at SentryContextManager.with (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:1376:24)     
    at ContextAPI.with (webpack-internal:///(instrument)/./node_modules/@opentelemetry/api/build/esm/api/context.js:95:54)
    at Object.withScope (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:1249:28)
    at Object.withScope (webpack-internal:///(rsc)/./node_modules/@sentry/core/build/cjs/currentScopes.js:61:14)
    at eval (webpack-internal:///(rsc)/./node_modules/@sentry/nextjs/build/cjs/common/wrapServerComponentWithSentry.js:51:21)
    at eval (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:1285:14)
    at AsyncLocalStorage.run (node:internal/async_local_storage/async_hooks:91:14)
    at SentryContextManager.with (webpack-internal:///(instrument)/./node_modules/@opentelemetry/context-async-hooks/build/src/AsyncLocalStorageContextManager.js:33:40)
    at SentryContextManager.with (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:1376:24)     
    at ContextAPI.with (webpack-internal:///(instrument)/./node_modules/@opentelemetry/api/build/esm/api/context.js:95:54)
    at Object.withSetIsolationScope (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:1284:28)  
    at Object.withIsolationScope (webpack-internal:///(rsc)/./node_modules/@sentry/core/build/cjs/currentScopes.js:93:16)
    at Object.apply (webpack-internal:///(rsc)/./node_modules/@sentry/nextjs/build/cjs/common/wrapServerComponentWithSentry.js:50:19)   
    at Object.apply (webpack-internal:///(rsc)/./app/(root)/page.tsx:152:10)
    at eval (webpack-internal:///(rsc)/./node_modules/@sentry/nextjs/build/cjs/common/wrapServerComponentWithSentry.js:67:40)
    at Object.handleCallbackErrors (webpack-internal:///(rsc)/./node_modules/@sentry/core/build/cjs/utils/handleCallbackErrors.js:26:26)
    at eval (webpack-internal:///(rsc)/./node_modules/@sentry/nextjs/build/cjs/common/wrapServerComponentWithSentry.js:66:27)
    at eval (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:955:15)
    at Object.handleCallbackErrors (webpack-internal:///(instrument)/./node_modules/@sentry/core/build/cjs/utils/handleCallbackErrors.js:26:26)
    at eval (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:954:19)
    at AsyncLocalStorage.run (node:internal/async_local_storage/async_hooks:91:14)
    at SentryContextManager.with (webpack-internal:///(instrument)/./node_modules/@opentelemetry/context-async-hooks/build/src/AsyncLocalStorageContextManager.js:33:40)
    at SentryContextManager.with (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:1376:24)     
    at ContextAPI.with (webpack-internal:///(instrument)/./node_modules/@opentelemetry/api/build/esm/api/context.js:95:54)
    at Tracer.startActiveSpan (webpack-internal:///(instrument)/./node_modules/@opentelemetry/sdk-trace-base/build/esm/Tracer.js:136:76)
    at eval (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:953:19)
    at eval (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:1148:21)
    at Object.startSpanManual (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:946:10)
    at Object.startSpanManual (webpack-internal:///(rsc)/./node_modules/@sentry/core/build/cjs/tracing/trace.js:90:16)
    at eval (webpack-internal:///(rsc)/./node_modules/@sentry/nextjs/build/cjs/common/wrapServerComponentWithSentry.js:56:23)
    at eval (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:1250:14)
    at AsyncLocalStorage.run (node:internal/async_local_storage/async_hooks:91:14)
    at SentryContextManager.with (webpack-internal:///(instrument)/./node_modules/@opentelemetry/context-async-hooks/build/src/AsyncLocalStorageContextManager.js:33:40)
    at SentryContextManager.with (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:1376:24)     
Error: No session
    at createSessionClient (webpack-internal:///(rsc)/./lib/appwrite.ts:21:15)
    at getLoggedInUser (webpack-internal:///(rsc)/./lib/actions/user.actions.ts:115:97)
    at RootLayout (webpack-internal:///(rsc)/./app/(root)/layout.tsx:32:102)
    at eval (webpack-internal:///(rsc)/./node_modules/@sentry/nextjs/build/cjs/common/wrapServerComponentWithSentry.js:67:40)
    at Object.handleCallbackErrors (webpack-internal:///(rsc)/./node_modules/@sentry/core/build/cjs/utils/handleCallbackErrors.js:26:26)
    at eval (webpack-internal:///(rsc)/./node_modules/@sentry/nextjs/build/cjs/common/wrapServerComponentWithSentry.js:66:27)
    at eval (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:955:15)
    at Object.handleCallbackErrors (webpack-internal:///(instrument)/./node_modules/@sentry/core/build/cjs/utils/handleCallbackErrors.js:26:26)
    at eval (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:954:19)
    at AsyncLocalStorage.run (node:internal/async_local_storage/async_hooks:91:14)
    at SentryContextManager.with (webpack-internal:///(instrument)/./node_modules/@opentelemetry/context-async-hooks/build/src/AsyncLocalStorageContextManager.js:33:40)
    at SentryContextManager.with (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:1376:24)     
    at ContextAPI.with (webpack-internal:///(instrument)/./node_modules/@opentelemetry/api/build/esm/api/context.js:95:54)
    at Tracer.startActiveSpan (webpack-internal:///(instrument)/./node_modules/@opentelemetry/sdk-trace-base/build/esm/Tracer.js:136:76)
    at eval (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:953:19)
    at eval (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:1148:21)
    at Object.startSpanManual (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:946:10)
    at Object.startSpanManual (webpack-internal:///(rsc)/./node_modules/@sentry/core/build/cjs/tracing/trace.js:90:16)
    at eval (webpack-internal:///(rsc)/./node_modules/@sentry/nextjs/build/cjs/common/wrapServerComponentWithSentry.js:56:23)
    at eval (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:1250:14)
    at AsyncLocalStorage.run (node:internal/async_local_storage/async_hooks:91:14)
    at SentryContextManager.with (webpack-internal:///(instrument)/./node_modules/@opentelemetry/context-async-hooks/build/src/AsyncLocalStorageContextManager.js:33:40)
    at SentryContextManager.with (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:1376:24)     
    at ContextAPI.with (webpack-internal:///(instrument)/./node_modules/@opentelemetry/api/build/esm/api/context.js:95:54)
    at Object.withScope (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:1249:28)
    at Object.withScope (webpack-internal:///(rsc)/./node_modules/@sentry/core/build/cjs/currentScopes.js:61:14)
    at eval (webpack-internal:///(rsc)/./node_modules/@sentry/nextjs/build/cjs/common/wrapServerComponentWithSentry.js:51:21)
    at eval (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:1285:14)
    at AsyncLocalStorage.run (node:internal/async_local_storage/async_hooks:91:14)
    at SentryContextManager.with (webpack-internal:///(instrument)/./node_modules/@opentelemetry/context-async-hooks/build/src/AsyncLocalStorageContextManager.js:33:40)
    at SentryContextManager.with (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:1376:24)     
    at ContextAPI.with (webpack-internal:///(instrument)/./node_modules/@opentelemetry/api/build/esm/api/context.js:95:54)
    at Object.withSetIsolationScope (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:1284:28)  
    at Object.withIsolationScope (webpack-internal:///(rsc)/./node_modules/@sentry/core/build/cjs/currentScopes.js:93:16)
    at Object.apply (webpack-internal:///(rsc)/./node_modules/@sentry/nextjs/build/cjs/common/wrapServerComponentWithSentry.js:50:19)   
    at Object.apply (webpack-internal:///(rsc)/./app/(root)/layout.tsx:124:10)
    at eval (webpack-internal:///(rsc)/./node_modules/@sentry/nextjs/build/cjs/common/wrapServerComponentWithSentry.js:67:40)
    at Object.handleCallbackErrors (webpack-internal:///(rsc)/./node_modules/@sentry/core/build/cjs/utils/handleCallbackErrors.js:26:26)
    at eval (webpack-internal:///(rsc)/./node_modules/@sentry/nextjs/build/cjs/common/wrapServerComponentWithSentry.js:66:27)
    at eval (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:955:15)
    at Object.handleCallbackErrors (webpack-internal:///(instrument)/./node_modules/@sentry/core/build/cjs/utils/handleCallbackErrors.js:26:26)
    at eval (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:954:19)
    at AsyncLocalStorage.run (node:internal/async_local_storage/async_hooks:91:14)
    at SentryContextManager.with (webpack-internal:///(instrument)/./node_modules/@opentelemetry/context-async-hooks/build/src/AsyncLocalStorageContextManager.js:33:40)
    at SentryContextManager.with (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:1376:24)     
    at ContextAPI.with (webpack-internal:///(instrument)/./node_modules/@opentelemetry/api/build/esm/api/context.js:95:54)
    at Tracer.startActiveSpan (webpack-internal:///(instrument)/./node_modules/@opentelemetry/sdk-trace-base/build/esm/Tracer.js:136:76)
    at eval (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:953:19)
    at eval (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:1148:21)
    at Object.startSpanManual (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:946:10)
    at Object.startSpanManual (webpack-internal:///(rsc)/./node_modules/@sentry/core/build/cjs/tracing/trace.js:90:16)
    at eval (webpack-internal:///(rsc)/./node_modules/@sentry/nextjs/build/cjs/common/wrapServerComponentWithSentry.js:56:23)
    at eval (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:1250:14)
    at AsyncLocalStorage.run (node:internal/async_local_storage/async_hooks:91:14)
    at SentryContextManager.with (webpack-internal:///(instrument)/./node_modules/@opentelemetry/context-async-hooks/build/src/AsyncLocalStorageContextManager.js:33:40)
    at SentryContextManager.with (webpack-internal:///(instrument)/./node_modules/@sentry/opentelemetry/build/cjs/index.js:1376:24)     
 GET / 307 in 38360ms
 ○ Compiling /sign-in ...
 ✓ Compiled /sign-in in 34.1s (3534 modules)
 GET /sign-in 200 in 30696ms
 ○ Compiling /sign-up ...
 ✓ Compiled /sign-up in 2s (3536 modules)
 GET /sign-up?_rsc=1m2hx 200 in 243ms
 ✓ Compiled in 1851ms (3265 modules)
 GET /sign-up?_rsc=bzjzl 200 in 1147ms
 ✓ Compiled in 1346ms (677 modules)
 GET /sign-up?_rsc=x2le1 200 in 31ms
Creating a Dwolla Customer Failed:  Error: {"code":"ValidationError","message":"Validation error(s) present. See embedded errors list for more details.","_embedded":{"errors":[{"code":"InvalidFormat","message":"Ssn invalid.","path":"/ssn","_links":{}}]}}
    at errorFrom (webpack-internal:///(action-browser)/./node_modules/dwolla-v2/src/dwolla/Token.js:52:15)
    at eval (webpack-internal:///(action-browser)/./node_modules/dwolla-v2/src/dwolla/Token.js:73:29)
From previous event:
    at handleResponse (webpack-internal:///(action-browser)/./node_modules/dwolla-v2/src/dwolla/Token.js:60:21)
From previous event:
    at Token.post (webpack-internal:///(action-browser)/./node_modules/dwolla-v2/src/dwolla/Token.js:95:6)
    at eval (webpack-internal:///(action-browser)/./node_modules/dwolla-v2/src/dwolla/Client.js:66:25)
    at process.processImmediate (node:internal/timers:491:21)
    at process.callbackTrampoline (node:internal/async_hooks:130:17)
From previous event:
    at Client.post (webpack-internal:///(action-browser)/./node_modules/dwolla-v2/src/dwolla/Client.js:65:23)
    at $$ACTION_2 (webpack-internal:///(action-browser)/./lib/actions/dwolla.actions.ts:64:35)
    at $$ACTION_2 (webpack-internal:///(action-browser)/./lib/actions/user.actions.ts:89:110)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:39:418
    at async rS (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:38:7978)
    at async r2 (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:41:1251)
    at async doRender (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\base-server.js:1438:30)
    at async cacheEntry.responseCache.get.routeKind (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\base-server.js:1599:28)
    at async DevServer.renderToResponseWithComponentsImpl (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\base-server.js:1507:28)
    at async DevServer.renderPageComponent (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\base-server.js:1924:24)       
    at async DevServer.renderToResponseImpl (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\base-server.js:1962:32)      
    at async DevServer.pipeImpl (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\base-server.js:920:25)
    at async NextNodeServer.handleCatchallRenderRequest (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\next-server.js:272:17)
    at async DevServer.handleRequestImpl (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\base-server.js:816:17)
    at async C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\dev\next-dev-server.js:336:24)      
    at async invokeRender (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\lib\router-server.js:174:21)
    at async handleRequest (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\lib\router-server.js:353:24)
    at async requestHandlerImpl (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\lib\router-server.js:377:13)
    at async Server.requestListener (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\lib\start-server.js:141:13) {        
  status: 400,
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      date: [Array],
      'content-type': [Array],
      'content-length': [Array],
      connection: [Array],
      'access-control-allow-origin': [Array],
      'x-request-id': [Array],
      'cf-cache-status': [Array],
      'set-cookie': [Array],
      server: [Array],
      'cf-ray': [Array]
    }
  },
  body: {
    code: 'ValidationError',
    message: 'Validation error(s) present. See embedded errors list for more details.',
    _embedded: { errors: [Array] }
  }
}
Error Error: Error creating Dwolla customer
    at $$ACTION_2 (webpack-internal:///(action-browser)/./lib/actions/user.actions.ts:93:39)
    at async C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:39:418
    at async rS (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:38:7978)
    at async r2 (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:41:1251)
    at async doRender (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\base-server.js:1438:30)
    at async cacheEntry.responseCache.get.routeKind (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\base-server.js:1599:28)
    at async DevServer.renderToResponseWithComponentsImpl (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\base-server.js:1507:28)
    at async DevServer.renderPageComponent (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\base-server.js:1924:24)       
    at async DevServer.renderToResponseImpl (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\base-server.js:1962:32)      
    at async DevServer.pipeImpl (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\base-server.js:920:25)
    at async NextNodeServer.handleCatchallRenderRequest (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\next-server.js:272:17)
    at async DevServer.handleRequestImpl (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\base-server.js:816:17)
    at async C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\dev\next-dev-server.js:336:24)      
    at async invokeRender (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\lib\router-server.js:174:21)
    at async handleRequest (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\lib\router-server.js:353:24)
    at async requestHandlerImpl (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\lib\router-server.js:377:13)
    at async Server.requestListener (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\lib\start-server.js:141:13)
 POST /sign-up 200 in 5463ms






    at async C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\dev\next-dev-server.js:336:24)      
    at async invokeRender (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\lib\router-server.js:174:21)
    at async handleRequest (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\lib\router-server.js:353:24)
    at async requestHandlerImpl (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\lib\router-server.js:377:13)
    at async Server.requestListener (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\lib\start-server.js:141:13)
    at async C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\dev\next-dev-server.js:336:24)      
    at async invokeRender (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\lib\router-server.js:174:21)
    at async handleRequest (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\lib\router-server.js:353:24)
    at async requestHandlerImpl (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\lib\router-server.js:377:13)
    at async Server.requestListener (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\lib\start-server.js:141:13)
 POST /sign-up 200 in 5463ms


    at async Span.traceAsyncFn (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\dev\next-dev-server.js:336:24)      
    at async invokeRender (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\lib\router-server.js:174:21)
    at async handleRequest (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\lib\router-server.js:353:24)
    at async requestHandlerImpl (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\lib\router-server.js:377:13)
    at async Server.requestListener (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\lib\start-server.js:141:13)
    at async requestHandlerImpl (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\lib\router-server.js:377:13)
    at async Server.requestListener (C:\Users\david\Desktop\xeniaPay\node_modules\next\dist\server\lib\start-server.js:141:13)
 POST /sign-up 200 in 5463ms


 POST /sign-up 200 in 5463ms

 POST /sign-up 200 in 5463ms
 POST /sign-up 200 in 5463ms





 POST /sign-up 200 in 5463ms



 POST /sign-up 200 in 5463ms
 POST /sign-up 200 in 5463ms





 POST /sign-up 200 in 5463ms

 POST /sign-up 200 in 5463ms
 POST /sign-up 200 in 5463ms
 GET /sign-up 200 in 3442ms

Now I get a problem with my ssn format which i'm not sure how i messed up the format.

**Comment by Jizzyjay** [comment]
i'm also having the same error

**Comment by rejoicedo** [comment]
Have any of you been able to solve this?

**Comment by Jizzyjay** [comment]
> Have any of you been able to solve this?

Yes

**Comment by Emmanuel-Ejeagha** [comment]
> > Have any of you been able to solve this?
> 
> Yes

How?
