### ISSUE TITLE
Error AppwriteException [Error]: Invalid relationship value.

### ISSUE THREAD

**Issue by mishdgr8** [adrianhajdin/banking#62]
Error AppwriteException [Error]: Invalid relationship value. Must be either an array of documents or document IDs, document ID given.
    at Client.call (webpack-internal:///(action-browser)/./node_modules/node-appwrite/lib/client.js:206:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Databases.createDocument (webpack-internal:///(action-browser)/./node_modules/node-appwrite/lib/services/databases.js:1711:16)
    at async $$ACTION_2 (webpack-internal:///(action-browser)/./lib/actions/user.actions.ts:95:25)
    at async /Users/mishdgr8/Desktop/banking/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:418
    at async rS (/Users/mishdgr8/Desktop/banking/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:38:7978)
    at async r2 (/Users/mishdgr8/Desktop/banking/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:41:1251)
    at async doRender (/Users/mishdgr8/Desktop/banking/node_modules/next/dist/server/base-server.js:1438:30)
    at async cacheEntry.responseCache.get.routeKind (/Users/mishdgr8/Desktop/banking/node_modules/next/dist/server/base-server.js:1599:28)
    at async DevServer.renderToResponseWithComponentsImpl (/Users/mishdgr8/Desktop/banking/node_modules/next/dist/server/base-server.js:1507:28)
    at async DevServer.renderPageComponent (/Users/mishdgr8/Desktop/banking/node_modules/next/dist/server/base-server.js:1924:24)
    at async DevServer.renderToResponseImpl (/Users/mishdgr8/Desktop/banking/node_modules/next/dist/server/base-server.js:1962:32)
    at async DevServer.pipeImpl (/Users/mishdgr8/Desktop/banking/node_modules/next/dist/server/base-server.js:920:25)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/mishdgr8/Desktop/banking/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/Users/mishdgr8/Desktop/banking/node_modules/next/dist/server/base-server.js:816:17)
    at async /Users/mishdgr8/Desktop/banking/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Users/mishdgr8/Desktop/banking/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/Users/mishdgr8/Desktop/banking/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/Users/mishdgr8/Desktop/banking/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/Users/mishdgr8/Desktop/banking/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/Users/mishdgr8/Desktop/banking/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/Users/mishdgr8/Desktop/banking/node_modules/next/dist/server/lib/start-server.js:141:13) {
  code: 400,
  type: 'relationship_value_invalid',
  response: {
    message: 'Invalid relationship value. Must be either an array of documents or document IDs, document ID given.',
    code: 400,
    type: 'relationship_value_invalid',
    version: '1.6.0'
  }
}

I have tried everything, somebody please help me out

**Comment by salahbm** [comment]
@mishdgr8 , Hello, could you solve this issue?
