### ISSUE TITLE
cannot able to connect dwolla account 

### ISSUE THREAD

**Issue by SrujanChary-2003** [adrianhajdin/banking#67]
Creating a Dwolla Customer Failed:  Error: {"code":"ValidationError","message":"Validation error(s) present. See embedded errors list for more details.","_embedded":{"errors":[{"code":"Required","message":"DateOfBirth required.","path":"/dateOfBirth","_links":{}}]}}
    at errorFrom (webpack-internal:///(action-browser)/./node_modules/dwolla-v2/src/dwolla/Token.js:52:15)  
    at eval (webpack-internal:///(action-browser)/./node_modules/dwolla-v2/src/dwolla/Token.js:73:29)       
From previous event:
    at handleResponse (webpack-internal:///(action-browser)/./node_modules/dwolla-v2/src/dwolla/Token.js:60:21)
From previous event:
    at Token.post (webpack-internal:///(action-browser)/./node_modules/dwolla-v2/src/dwolla/Token.js:95:6)  
    at eval (webpack-internal:///(action-browser)/./node_modules/dwolla-v2/src/dwolla/Client.js:66:25)      
    at process.processImmediate (node:internal/timers:478:21)
    at process.callbackTrampoline (node:internal/async_hooks:130:17)
From previous event:
    at Client.post (webpack-internal:///(action-browser)/./node_modules/dwolla-v2/src/dwolla/Client.js:65:23)
    at $$ACTION_2 (webpack-internal:///(action-browser)/./lib/actions/dwolla.actions.ts:64:35)
    at $$ACTION_2 (webpack-internal:///(action-browser)/./lib/actions/user.actions.ts:88:110)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:39:418
    at async r_ (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:38:8148)
    at async r8 (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:41:1256)
    at async doRender (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\server\base-server.js:1406:30)
    at async cacheEntry.responseCache.get.routeKind (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\server\base-server.js:1567:28)
    at async DevServer.renderToResponseWithComponentsImpl (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\server\base-server.js:1475:28)
    at async DevServer.renderPageComponent (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\server\base-server.js:1901:24)
    at async DevServer.renderToResponseImpl (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\server\base-server.js:1939:32)
    at async DevServer.pipeImpl (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\server\base-server.js:914:25)
    at async NextNodeServer.handleCatchallRenderRequest (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\server\next-server.js:272:17)
    at async DevServer.handleRequestImpl (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\server\base-server.js:810:17)
    at async C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\server\lib\router-server.js:173:21)
    at async handleRequest (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\server\lib\router-server.js:350:24)
    at async requestHandlerImpl (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\server\lib\router-server.js:374:13)
    at async Server.requestListener (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\server\lib\start-server.js:141:13) {
  status: 400,
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      date: [Array],
      'content-type': [Array],
      'content-length': [Array],
      connection: [Array],
      'access-control-allow-origin': [Array],
      'x-request-id': [Array],
      'cf-cache-status': [Array],
      'set-cookie': [Array],
      server: [Array],
      'cf-ray': [Array]
    }
  },
  body: {
    code: 'ValidationError',
    message: 'Validation error(s) present. See embedded errors list for more details.',
    _embedded: { errors: [Array] }
  }
}
Error Error: Error creating Dwolla customer
    at $$ACTION_2 (webpack-internal:///(action-browser)/./lib/actions/user.actions.ts:92:39)
    at async C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:39:418
    at async r_ (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:38:8148)
    at async r8 (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:41:1256)
    at async doRender (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\server\base-server.js:1406:30)
    at async cacheEntry.responseCache.get.routeKind (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\server\base-server.js:1567:28)
    at async DevServer.renderToResponseWithComponentsImpl (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\server\base-server.js:1475:28)
    at async DevServer.renderPageComponent (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\server\base-server.js:1901:24)
    at async DevServer.renderToResponseImpl (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\server\base-server.js:1939:32)
    at async DevServer.pipeImpl (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\server\base-server.js:914:25)
    at async NextNodeServer.handleCatchallRenderRequest (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\server\next-server.js:272:17)
    at async DevServer.handleRequestImpl (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\server\base-server.js:810:17)
    at async C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\server\lib\router-server.js:173:21)
    at async handleRequest (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\server\lib\router-server.js:350:24)
    at async requestHandlerImpl (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\server\lib\router-server.js:374:13)
    at async Server.requestListener (C:\Users\Srujan charry\Desktop\demo\banking\node_modules\next\dist\server\lib\start-server.js:141:13)

Please solve the issue sir

**Comment by beginner154** [comment]
Have same problem here

**Comment by beginner154** [comment]
@SrujanChary-2003 I solved the problem
First of all,make sure  that every field of yours in database attributes and in your code(everywhere) has following syntaxfirstName: string;
  lastName: string;
  name: string
  address1: string;
  city: string;
  state: string;
  postalCode: string;
  dateOfBirth: string;
  ssn: string
Especially address1,it seems that dwolla accepts it as address1 variable only
Second of all use fake address  generator with every data which is close to real one,as you use dwolla so it accepts not every nonsense data that user may enter
https://www.fakexy.com/us-fake-address-generator-nh
After it you should get to your "Connect bank" button and in case if it is disabled(not bright-blue) just rerun application with npm run dev and you should be logged in

**Comment by ArayAguiar** [comment]
Don't know if you are still having the same issue, but I was having issues

1.  if I created a "test account" with the same email creating the DWOLLA account, I tried a different email and it worked without any problem;
2. The date format apparently was also an issue, as it only went through if I put the date of birth in the format YYYY-MM-DD;

**Comment by hridoysaha969** [comment]
Did anyone solve this issue?
