### ISSUE TITLE
after creating dwolla account again this error is coming

### ISSUE THREAD

**Issue by Sohaib-glitch-oops** [adrianhajdin/banking#80]
Error: Dwolla environment should either be set to `sandbox` or `production`
    at getEnvironment (webpack-internal:///(rsc)/./lib/actions/dwolla.actions.ts:26:19)
    at eval (webpack-internal:///(rsc)/./lib/actions/dwolla.actions.ts:30:18)
    at (rsc)/./lib/actions/dwolla.actions.ts (file://C:\Users\akram\OneDrive\Desktop\jsm_banking\.next\server\app\(root)\page.js:1965:1)
    at __webpack_require__ (file://C:\Users\akram\OneDrive\Desktop\jsm_banking\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./lib/actions/user.actions.ts:25:73)
    at (rsc)/./lib/actions/user.actions.ts (file://C:\Users\akram\OneDrive\Desktop\jsm_banking\.next\server\app\(root)\page.js:1987:1)
    at __webpack_require__ (file://C:\Users\akram\OneDrive\Desktop\jsm_banking\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./app/(root)/layout.tsx:18:83)
    at (rsc)/./app/(root)/layout.tsx (file://C:\Users\akram\OneDrive\Desktop\jsm_banking\.next\server\app\(root)\page.js:1261:1)
    at Function.__webpack_require__ (file://C:\Users\akram\OneDrive\Desktop\jsm_banking\.next\server\webpack-runtime.js:33:43)
    at async getLayoutOrPageModule (file://C:\Users\akram\OneDrive\Desktop\jsm_banking\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:157:10758)
    at async createComponentTreeInternal (file://C:\Users\akram\OneDrive\Desktop\jsm_banking\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:157:17521)
    at async (file://C:\Users\akram\OneDrive\Desktop\jsm_banking\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:157:22238)
    at async createComponentTreeInternal (file://C:\Users\akram\OneDrive\Desktop\jsm_banking\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:157:21462)
    at async getRSCPayload (file://C:\Users\akram\OneDrive\Desktop\jsm_banking\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:161:6229)
    at async renderToStream (file://C:\Users\akram\OneDrive\Desktop\jsm_banking\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:161:30340)
    at async renderToHTMLOrFlightImpl (file://C:\Users\akram\OneDrive\Desktop\jsm_banking\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:161:19738)
    at async doRender (file://C:\Users\akram\OneDrive\Desktop\jsm_banking\node_modules\next\dist\server\base-server.js:1587:34)
    at async responseGenerator (file://C:\Users\akram\OneDrive\Desktop\jsm_banking\node_modules\next\dist\server\base-server.js:1834:28)
    at async DevServer.renderToResponseWithComponentsImpl (file://C:\Users\akram\OneDrive\Desktop\jsm_banking\node_modules\next\dist\server\base-server.js:1876:28)
    at async DevServer.renderPageComponent (file://C:\Users\akram\OneDrive\Desktop\jsm_banking\node_modules\next\dist\server\base-server.js:2290:24)
    at async DevServer.renderToResponseImpl (file://C:\Users\akram\OneDrive\Desktop\jsm_banking\node_modules\next\dist\server\base-server.js:2328:32)
    at async DevServer.pipeImpl (file://C:\Users\akram\OneDrive\Desktop\jsm_banking\node_modules\next\dist\server\base-server.js:984:25)
    at async NextNodeServer.handleCatchallRenderRequest (file://C:\Users\akram\OneDrive\Desktop\jsm_banking\node_modules\next\dist\server\next-server.js:281:17)
    at async DevServer.handleRequestImpl (file://C:\Users\akram\OneDrive\Desktop\jsm_banking\node_modules\next\dist\server\base-server.js:877:17)
    at async (file://C:\Users\akram\OneDrive\Desktop\jsm_banking\node_modules\next\dist\server\dev\next-dev-server.js:373:20)
    at async Span.traceAsyncFn (file://C:\Users\akram\OneDrive\Desktop\jsm_banking\node_modules\next\dist\trace\trace.js:153:20)
    at async DevServer.handleRequest (file://C:\Users\akram\OneDrive\Desktop\jsm_banking\node_modules\next\dist\server\dev\next-dev-server.js:370:24)
    at async invokeRender (file://C:\Users\akram\OneDrive\Desktop\jsm_banking\node_modules\next\dist\server\lib\router-server.js:183:21)
    at async handleRequest (file://C:\Users\akram\OneDrive\Desktop\jsm_banking\node_modules\next\dist\server\lib\router-server.js:360:24)
    at async requestHandlerImpl (file://C:\Users\akram\OneDrive\Desktop\jsm_banking\node_modules\next\dist\server\lib\router-server.js:384:13)
    at async Server.requestListener (file://C:\Users\akram\OneDrive\Desktop\jsm_banking\node_modules\next\dist\server\lib\start-server.js:142:13)

**Comment by JITs10** [comment]
have you resolved this error ? i am getting the same one
